#name: RISC-V Compliance tests
#on: [push, pull_request]

#jobs:
  #build_nox_sim:
    #runs-on: ubuntu-latest
    #steps:
      #- name: Install Verilator
        #uses: actions/checkout@v2
      #- run: |
          #sudo apt-get update -y
          #sudo apt-get upgrade -y
          #sudo apt install -y --no-install-recommends make g++ perl python3 autoconf flex bison libfl2 libfl-dev zlibc zlib1g zlib1g-dev
          #git clone https://github.com/verilator/verilator.git
          #cd verilator
          #git checkout stable
          #autoconf
          #./configure
          #make -j $(nproc)
          #sudo make install
      #- name: Build model DUT
        #uses: actions/checkout@v2
      #- run: |
          #make all RUN_CMD="" RV_COMPLIANCE=1 IRAM_KB_SIZE=2048 DRAM_KB_SIZE=128 WAVEFORM_USE=0
      #- uses: actions/upload-artifact@master
        #with:
          #name: nox_sim
          #path: output_verilator/nox_sim
  #run_compliance:
    #needs: build_nox_sim
    #runs-on: ubuntu-latest
    #steps:
      #- name: Install RISC-V toolchain
        #uses: actions/checkout@master
      #- run: |
          #wget -c https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack/releases/download/v10.2.0-1.2/xpack-riscv-none-embed-gcc-10.2.0-1.2-linux-x64.tar.gz -O - | tar -xz
          #sudo cp -rf xpack-riscv-none-embed-gcc-10.2.0-1.2/ /opt
          #sudo ln -s /opt/xpack-riscv-none-embed-gcc-10.2.0-1.2/bin/riscv* /usr/bin
      #- name: Installing SAIL C-emulator
        #run: |
          #sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo "Europe/Dublin" > /etc/timezone
          #sudo apt-get install opam libgmp-dev z3 pkg-config zlib1g-dev -y
          #sudo opam init -y --disable-sandboxing
          #sudo opam switch create ocaml-base-compiler.4.06.1
          #sudo opam install sail -y
          #sudo eval $(opam config env)
          #sudo /bin/bash /root/.bashrc
          #sudo git clone https://github.com/riscv/sail-riscv.git
          #sudo eval $(opam config env) && make ARCH=RV32
          #sudo ln -s /opt/sail-riscv/c_emulator/riscv_sim_RV32 /usr/bin/riscv_sim_RV32
          #sudo echo "export PATH=\"$PATH:/sail-riscv/c_emulator/\""  >> /root/.bashrc
      #- name: Copy nox_sim
      #- run:  mkdir -p /tests/output_verilator
        #uses: actions/download-artifact@master
        #with:
          #name: nox_sim
          #path: /tests/output_verilator/nox_sim
      #- run: |
          #make compliance

