name: Linting
on: [push, pull_request]

jobs:
  lint_nox_sim:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Verilator
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt install -y --no-install-recommends make g++ perl python3 autoconf flex bison libfl2 libfl-dev zlibc zlib1g zlib1g-dev
          git clone https://github.com/verilator/verilator.git
          cd verilator
          git checkout stable
          autoconf
          ./configure
          make -j $(nproc)
          sudo make install
      - name: Build model DUT
        uses: actions/checkout@v3
      - run: |
          make RUN_CMD="" lint
